#
# Copyright (C) 2026 OrangeFox Recovery Project
#

export OF_KEEP_FORCED_ENCRYPTION=true
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_DEFAULT_KEYMASTER_VERSION=4.0
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_ENABLE_LPTOOLS=1
export OF_QUICK_BACKUP_LIST="/boot;/nvram;/nvdata;/protect_f;/protect_s;"
export FOX_ALLOW_EARLY_SETTINGS_LOAD="1"
export OF_NO_RELOAD_AFTER_DECRYPTION="1"
export OF_FIX_DECRYPTION_ON_DATA_MEDIA="1"
export OF_UNBIND_SDCARD_F2FS="1"
export OF_FBE_METADATA_MOUNT_IGNORE="1"
export OF_ADVANCED_SECURITY=1
export OF_DISABLE_DM_VERITY=1
export OF_FIX_DECRYPTION=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
export FOX_VARIANT=mt6765
export OF_MAINTAINER="secr5t"
export FOX_MAINTAINER_PATCH_VERSION="1"
export FOX_BUILD_TYPE="Unofficial"
